name: Micro-Manager
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from
collections:
  pages:
    output: true
    permalink: /:path
